### ISSUE TITLE
Can't send hex string.

### ISSUE THREAD

**Issue by fr33z3** [emqx/mqtt-jmeter#48]
I'm trying to send hex string:
`08B19ECCDD0542480A1608AB9ECCDD05120205072A06F603D40E182A300238030A1608AB9ECCDD05120200062A06F603D40E182A300338030A1608AB9ECCDD05120200062A06F603D40E182A30053801`

But getting the error:
```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at net.xmeter.samplers.PubSampler.hexToBinary(PubSampler.java:75) ~[mqtt-xmeter-1.0.1-jar-with-dependencies.jar:?]
	at net.xmeter.samplers.PubSampler.sample(PubSampler.java:100) ~[mqtt-xmeter-1.0.1-jar-with-dependencies.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```
Am I doing something wrong?

**Comment by jinfahua** [comment]
Could you try workaround in link - https://github.com/http-kit/http-kit/issues/356

**Comment by JarvisPongSky** [comment]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at net.xmeter.samplers.PubSampler.hexToBinary(PubSampler.java:86) ~[mqtt-xmeter-2.0.2-jar-with-dependencies.jar:?]
	at net.xmeter.samplers.PubSampler.sample(PubSampler.java:112) ~[mqtt-xmeter-2.0.2-jar-with-dependencies.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) ~[ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:834) [?:?]
